--CATEGORY 테이블 시퀀스
CREATE SEQUENCE CATEGORY_SEQ
START WITH 1  
INCREMENT BY 1  
NOCACHE
NOCYCLE; 


--CATEGORY 테이블 생성
CREATE TABLE CATEGORY (
    CATEGORY_ID NUMBER(10) NOT NULL,  -- 시퀀스로 값을 채움
    PARENTS_CATEGORY_ID NUMBER(10) NOT NULL,  -- FK
    CATEGORY_NAME VARCHAR2(255) NOT NULL,
    CATEGORY_LEVEL NUMBER(10) NOT NULL,
    CONSTRAINT CHK_CATEGORY_LEVEL CHECK (CATEGORY_LEVEL IN (1, 2, 3)),  -- 제약 조건: CATEGORY_LEVEL은 1, 2, 3만 허용
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID),  -- 기본키 설정
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENTS_CATEGORY_ID)  -- 외래키 설정
    REFERENCES CATEGORY (CATEGORY_ID)  -- 부모 테이블의 PK 참조
);


-- PARENTS_CATEGORY_ID를 NULL 허용으로 변경
ALTER TABLE CATEGORY 
MODIFY PARENTS_CATEGORY_ID NUMBER(10) NULL;


-- CATEGORY_ID에 시퀀스를 통해 자동으로 값 입력
CREATE OR REPLACE TRIGGER TRG_CATEGORY_ID
BEFORE INSERT ON CATEGORY
FOR EACH ROW
BEGIN
    :NEW.CATEGORY_ID := CATEGORY_SEQ.NEXTVAL;  -- 시퀀스에서 값 가져오기
END TRG_CATEGORY_ID;  -- 트리거 이름을 붙여서 종료
/

-- CATEGORY 테이블 임시 데이터 추가
INSERT INTO CATEGORY (PARENTS_CATEGORY_ID, CATEGORY_NAME, CATEGORY_LEVEL)
VALUES (NULL, '의류', 1);


--PRODUCTS 테이블 시퀀스
CREATE SEQUENCE PRODUCT_SEQ
START WITH 1  
INCREMENT BY 1  
NOCACHE  
NOCYCLE;  


--PRODUCTS 테이블 생성
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER(10) NOT NULL,  -- 시퀀스 값으로 채워질 기본키
    CATEGORY_ID NUMBER(10) NOT NULL,  -- 외래키 설정 필요
    PRODUCT_NAME VARCHAR2(150) NOT NULL,
    IMG1 VARCHAR2(600) NOT NULL,
    IMG2 VARCHAR2(600) NULL,
    IMG3 VARCHAR2(600) NULL,
    PRODUCT_CONTENT VARCHAR2(1000) NULL,
    PRICE NUMBER(10,2) NOT NULL,
    STOCK_QUANTITY NUMBER(10) NOT NULL,
    REGISTRATION_DATE DATE NOT NULL,
    BRAND VARCHAR2(50) NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID),  -- 기본키로 설정
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID),  -- 외래키 설정
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('판매중', '판매중지', '품절') )  -- 상태 제약조건 설정
);

--조건 추가
ALTER TABLE PRODUCTS
MODIFY STATUS VARCHAR2(20) DEFAULT '판매중';
ALTER TABLE PRODUCTS
MODIFY REGISTRATION_DATE DATE DEFAULT SYSDATE;


-- 트리거 생성: 삽입 전에 자동으로 시퀀스 값 설정
CREATE OR REPLACE TRIGGER TRG_PRODUCTS_ID
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
    :NEW.PRODUCT_ID := PRODUCT_SEQ.NEXTVAL;  -- 시퀀스의 다음 값을 PRODUCT_ID에 삽입
END TRG_PRODUCTS_ID;
/


-- 임시데이터 추가
INSERT INTO PRODUCTS (CATEGORY_ID, PRODUCT_NAME, IMG1, IMG2, IMG3, PRODUCT_CONTENT, PRICE, STOCK_QUANTITY, REGISTRATION_DATE, BRAND, STATUS)
VALUES (2, '청바지', 'img/jeans1.jpg', 'img/jeans2.jpg', NULL, '스타일리시한 청바지', 40000, 50, SYSDATE, '브랜드B', '판매중');



