name: Branch Name Check

on:
  push:
    branches:
      - '*'  # 모든 브랜치에 대해 체크

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          echo "Current branch: $GITHUB_REF"
          if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "Main branch, no checks required."
          elif [[ ! "$GITHUB_REF" =~ ^refs/heads/(feature)/ ]]; then
            echo "Branch name does not match the required format (feature/*)."
            exit 1
          fi
